name: Quarto Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    container:
        image: bioconductor/bioconductor_docker:devel
      
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Install curl
      #   run: |
      #     sudo apt-get install libcurl4-openssl-dev

      # - name: Setup Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2
      #   with:
      #     tinytex: true

      - name: Setup Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.43/quarto-1.5.43-linux-amd64.deb && \
          dpkg -i quarto-1.5.43-linux-amd64.deb && \
          rm quarto-1.5.43-linux-amd64.deb

      - name: Setup tinytex
        run: quarto install tinytex

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      #     cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Set directories
        run: |
          echo "R_PKG_DIR=${R_HOME}/site-library" >> $GITHUB_ENV

      - name: Restore the package directory
        uses: actions/cache@v3
        with:
          path: ${{ env.R_PKG_DIR }}
          key: check-packages

      - name: Install R packages
        run: Rscript rpackages.R

      # build SQLite from source, because I need 3.35<=
      - name: Download SQLite3
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz
          tar -xvf sqlite-autoconf-3450300.tar.gz

      - name: Install SQLite3
        run: |
          ./configure
          make
          sudo make install
          export PATH="/usr/local/lib:$PATH"
        working-directory: sqlite-autoconf-3450300

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: Publish to GH Pages
        if: github.ref == 'refs/heads/master'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # The branch the action should deploy to.
          render: false