name: Quarto Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt

      # build SQLite from source, because I need 3.35<=
      - name: Download SQLite3
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz
          tar -xvf sqlite-autoconf-3450300.tar.gz

      - name: Install SQLite3
        run: |
          cd sqlite-autoconf-3450300
          ./configure
          make
          sudo make install
          export PATH="/usr/local/lib:$PATH"
          cd ..

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: Publish to GH Pages
        if: github.ref == 'refs/heads/master'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # The branch the action should deploy to.
          render: false
